# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import speech_service_pb2 as speech__service__pb2


class SpeechServiceStub(object):
    """Service definition for speech processing operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudioSegment = channel.unary_unary(
                '/speech_service.SpeechService/TranscribeAudioSegment',
                request_serializer=speech__service__pb2.TranscribeAudioRequest.SerializeToString,
                response_deserializer=speech__service__pb2.TranscribeAudioResponse.FromString,
                )
        self.MergeTranscriptions = channel.unary_unary(
                '/speech_service.SpeechService/MergeTranscriptions',
                request_serializer=speech__service__pb2.MergeTranscriptionsRequest.SerializeToString,
                response_deserializer=speech__service__pb2.MergeTranscriptionsResponse.FromString,
                )
        self.ProcessIntent = channel.unary_unary(
                '/speech_service.SpeechService/ProcessIntent',
                request_serializer=speech__service__pb2.ProcessIntentRequest.SerializeToString,
                response_deserializer=speech__service__pb2.ProcessIntentResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/speech_service.SpeechService/HealthCheck',
                request_serializer=speech__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=speech__service__pb2.HealthCheckResponse.FromString,
                )


class SpeechServiceServicer(object):
    """Service definition for speech processing operations
    """

    def TranscribeAudioSegment(self, request, context):
        """Transcribe an audio segment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeTranscriptions(self, request, context):
        """Merge multiple transcriptions into a single text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessIntent(self, request, context):
        """Process text for intent analysis and entity extraction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for the model service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudioSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudioSegment,
                    request_deserializer=speech__service__pb2.TranscribeAudioRequest.FromString,
                    response_serializer=speech__service__pb2.TranscribeAudioResponse.SerializeToString,
            ),
            'MergeTranscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeTranscriptions,
                    request_deserializer=speech__service__pb2.MergeTranscriptionsRequest.FromString,
                    response_serializer=speech__service__pb2.MergeTranscriptionsResponse.SerializeToString,
            ),
            'ProcessIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessIntent,
                    request_deserializer=speech__service__pb2.ProcessIntentRequest.FromString,
                    response_serializer=speech__service__pb2.ProcessIntentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=speech__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=speech__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech_service.SpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeechService(object):
    """Service definition for speech processing operations
    """

    @staticmethod
    def TranscribeAudioSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speech_service.SpeechService/TranscribeAudioSegment',
            speech__service__pb2.TranscribeAudioRequest.SerializeToString,
            speech__service__pb2.TranscribeAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MergeTranscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speech_service.SpeechService/MergeTranscriptions',
            speech__service__pb2.MergeTranscriptionsRequest.SerializeToString,
            speech__service__pb2.MergeTranscriptionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speech_service.SpeechService/ProcessIntent',
            speech__service__pb2.ProcessIntentRequest.SerializeToString,
            speech__service__pb2.ProcessIntentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speech_service.SpeechService/HealthCheck',
            speech__service__pb2.HealthCheckRequest.SerializeToString,
            speech__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
